"""Pruning tables (heuristic distance tables) for Kociemba's two-phase solver.

Each pruning table is a ``bytearray`` indexed by a pair of coordinates; the
stored value is the minimum number of HTM moves needed to reach a state
whose coordinate pair matches the given one from the goal state. The
heuristic used by the search is the maximum over all applicable tables,
which stays admissible because each table is a lower bound on its own.

Phase 1 tables (18-move generator, goal = (twist=0, flip=0, slice=0)):
	twist_slice_prun:   distance to (twist=0, slice=0), ignoring flip.
	flip_slice_prun:    distance to (flip=0,  slice=0), ignoring twist.

Phase 2 tables (10-move generator, goal = (cp=0, ep_ud=0, sp=0)):
	cp_sp_prun:         distance to (cp=0,    sp=0), ignoring ep_ud.
	ep_ud_sp_prun:      distance to (ep_ud=0, sp=0), ignoring cp.

Tables are generated by a breadth-first search from the goal pair and
cached to disk under ``_tables/`` so the first invocation pays the
generation cost and subsequent invocations read the table in one shot.
"""
from __future__ import annotations

import os

from . import coord as cd
from . import moves as mv


INF = 255

TABLES_DIR = os.path.join(os.path.dirname(__file__), "_tables")


def _table_path(name: str) -> str:
	return os.path.join(TABLES_DIR, name + ".bin")


def _load_table(name: str, expected_size: int) -> bytearray | None:
	path = _table_path(name)
	try:
		with open(path, "rb") as f:
			data = f.read()
	except FileNotFoundError:
		return None
	if len(data) != expected_size:
		return None
	return bytearray(data)


def _save_table(name: str, table: bytearray) -> None:
	os.makedirs(TABLES_DIR, exist_ok=True)
	with open(_table_path(name), "wb") as f:
		f.write(bytes(table))


def _bfs_pair(
	move_a: list[list[int]],
	move_b: list[list[int]],
	size_b: int,
	moves_count: int,
	total_size: int,
) -> bytearray:
	"""BFS from goal (a=0, b=0) in the combined (a, b) coordinate space.

	``move_a`` and ``move_b`` are move tables for two independent
	coordinates. The combined index is ``a * size_b + b``. Distances
	are clipped at INF - 1 so they fit in a byte.
	"""
	table = bytearray([INF] * total_size)
	table[0] = 0
	current_layer = [0]
	depth = 0

	while current_layer:
		next_layer = []
		new_depth = depth + 1
		for idx in current_layer:
			a, b = divmod(idx, size_b)
			row_a = move_a[a]
			row_b = move_b[b]
			for mi in range(moves_count):
				ni = row_a[mi] * size_b + row_b[mi]
				if table[ni] == INF:
					table[ni] = new_depth
					next_layer.append(ni)
		current_layer = next_layer
		depth = new_depth
	return table


# --- Phase 1 pruning tables ---

_TWIST_SLICE_SIZE = cd.TWIST_COUNT * cd.SLICE_COUNT  # 2187 * 495
_FLIP_SLICE_SIZE = cd.FLIP_COUNT * cd.SLICE_COUNT    # 2048 * 495

_twist_slice_prun = None
_flip_slice_prun = None


def twist_slice_prun() -> bytearray:
	"""Phase 1 pruning table keyed by (twist, slice)."""
	global _twist_slice_prun
	if _twist_slice_prun is not None:
		return _twist_slice_prun
	cached = _load_table("twist_slice_prun", _TWIST_SLICE_SIZE)
	if cached is not None:
		_twist_slice_prun = cached
		return cached
	table = _bfs_pair(
		mv.twist_move(),
		mv.slice_move(),
		cd.SLICE_COUNT,
		mv.HTM_COUNT,
		_TWIST_SLICE_SIZE,
	)
	_save_table("twist_slice_prun", table)
	_twist_slice_prun = table
	return table


def flip_slice_prun() -> bytearray:
	"""Phase 1 pruning table keyed by (flip, slice)."""
	global _flip_slice_prun
	if _flip_slice_prun is not None:
		return _flip_slice_prun
	cached = _load_table("flip_slice_prun", _FLIP_SLICE_SIZE)
	if cached is not None:
		_flip_slice_prun = cached
		return cached
	table = _bfs_pair(
		mv.flip_move(),
		mv.slice_move(),
		cd.SLICE_COUNT,
		mv.HTM_COUNT,
		_FLIP_SLICE_SIZE,
	)
	_save_table("flip_slice_prun", table)
	_flip_slice_prun = table
	return table


# --- Phase 2 pruning tables ---

_CP_SP_SIZE = cd.CP_COUNT * cd.SP_COUNT            # 40320 * 24
_EP_UD_SP_SIZE = cd.EP_UD_COUNT * cd.SP_COUNT      # 40320 * 24

_cp_sp_prun = None
_ep_ud_sp_prun = None


def cp_sp_prun() -> bytearray:
	"""Phase 2 pruning table keyed by (cp, sp)."""
	global _cp_sp_prun
	if _cp_sp_prun is not None:
		return _cp_sp_prun
	cached = _load_table("cp_sp_prun", _CP_SP_SIZE)
	if cached is not None:
		_cp_sp_prun = cached
		return cached
	table = _bfs_pair(
		mv.cp_move(),
		mv.sp_move(),
		cd.SP_COUNT,
		mv.PHASE2_COUNT,
		_CP_SP_SIZE,
	)
	_save_table("cp_sp_prun", table)
	_cp_sp_prun = table
	return table


def ep_ud_sp_prun() -> bytearray:
	"""Phase 2 pruning table keyed by (ep_ud, sp)."""
	global _ep_ud_sp_prun
	if _ep_ud_sp_prun is not None:
		return _ep_ud_sp_prun
	cached = _load_table("ep_ud_sp_prun", _EP_UD_SP_SIZE)
	if cached is not None:
		_ep_ud_sp_prun = cached
		return cached
	table = _bfs_pair(
		mv.ep_ud_move(),
		mv.sp_move(),
		cd.SP_COUNT,
		mv.PHASE2_COUNT,
		_EP_UD_SP_SIZE,
	)
	_save_table("ep_ud_sp_prun", table)
	_ep_ud_sp_prun = table
	return table


def prewarm() -> None:
	"""Force all pruning tables to be generated / loaded."""
	twist_slice_prun()
	flip_slice_prun()
	cp_sp_prun()
	ep_ud_sp_prun()
